# Generated by Django 4.2.5 on 2023-10-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
