# Generated by Django 4.2.5 on 2023-10-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_record_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='picture',
        ),
    ]
