# Generated by Django 4.2.5 on 2023-10-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_record_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
